name: auth0_flutter_auth_example
description: Example app for auth0_flutter_auth with GoRouter.

publish_to: 'none'

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  auth0_flutter_auth:
    path: ../
  go_router: ^14.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  otp: ^3.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
